name: PlatformIO CI examples

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [-c ./examples/BMP180Example/platformio.ini ./examples/BMP180Example/,
                  -c ./examples/BMP280Example/platformio.ini ./examples/BMP280Example/,
                  -c ./examples/DHT11Example/platformio.ini ./examples/DHT11Example/,
                  -c ./examples/DuckLinkExample/platformio.ini ./examples/DuckLinkExample/,
                  -c ./examples/DustSensorExample/platformio.ini ./examples/DustSensorExample/,
                  -c ./examples/MamaDuckExample/platformio.ini ./examples/MamaDuckExample/,
                  -c ./examples/MQ7Example/platformio.ini ./examples/MQ7Example/,
                  -c ./examples/PapaDuckExample/platformio.ini ./examples/PapaDuckExample/]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        platformio lib -g install file://.

    - name: Run PlatformIO
      run: platformio ci --lib="." ${{ matrix.example }}
      with:
          name: binary
          path: .pio/build/heltec_wifi_lora_32_V2/firmware.elf
